// Generate src/version.ts from the package version, git short SHA and commit date.
// In environments without a .git directory (e.g. the Docker frontend stage), the
// GIT_HASH / BUILD_DATE environment variables are used as a fallback.
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const { version } = JSON.parse(readFileSync("package.json", "utf8"));

function git(cmd) {
  try {
    return execSync(cmd, { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

const sha = process.env.GIT_HASH || git("git rev-parse --short HEAD") || "unknown";
const date =
  process.env.BUILD_DATE || git("git log -1 --format=%cs") || "";

if (sha === "unknown") {
  console.warn(
    "gen-version: git SHA unavailable (no .git and no GIT_HASH env); using 'unknown'",
  );
}

const label = `v${version}-${sha}${date ? ` (${date})` : ""}`;

const out = `// Generated by scripts/gen-version.mjs — do not edit
export const VERSION = ${JSON.stringify(label)};
`;

writeFileSync("src/version.ts", out);
console.log(`version: ${label}`);
