import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const localesDir = join(here, "..", "locales");
const outFile = join(here, "..", "src", "locales.generated.ts");

const files = readdirSync(localesDir)
  .filter((f) => f.toLowerCase().endsWith(".json"))
  .sort();

const imports = files
  .map((f) => {
    const code = f.replace(/\.json$/i, "").toLowerCase();
    const varName = code.replace(/[^a-zA-Z0-9_]/g, "_");
    return `import ${varName} from "../locales/${f}";`;
  })
  .join("\n");

const entries = files
  .map((f) => {
    const code = f.replace(/\.json$/i, "").toLowerCase();
    const varName = code.replace(/[^a-zA-Z0-9_]/g, "_");
    return `  ${code}: ${varName} as unknown as Catalog,`;
  })
  .join("\n");

const content = `// AUTO-GENERATED by scripts/gen-i18n.mjs — do not edit.
// Rebuilt from every *.json file in locales/ (no language hard-coded in source).

${imports}

export type Catalog = Record<string, string>;

export const catalogs: Record<string, Catalog> = {
${entries}
};
`;

writeFileSync(outFile, content);
console.log(`gen-i18n: generated ${files.length} locale(s): ${files.join(", ")}`);
