// AUTO-GENERATED by scripts/gen-i18n.mjs — do not edit.
// Rebuilt from every *.json file in locales/ (no language hard-coded in source).

import en from "../locales/en.json";
import ja from "../locales/ja.json";

export type Catalog = Record<string, string>;

export const catalogs: Record<string, Catalog> = {
  en: en as unknown as Catalog,
  ja: ja as unknown as Catalog,
};
